# Generated by Django 5.2.7 on 2025-12-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'managed': True, 'ordering': ['album', 'track_number']},
        ),
    ]
